#!/system/bin/sh

echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "122880" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "787200" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "noop" > /sys/block/mmcblk0/queue/scheduler

