#!/system/bin/sh

echo "smartassH3" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "122880" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "600000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "deadline" > /sys/block/mmcblk0/queue/scheduler

